apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgre
spec:  
  selector:
    matchLabels:
      app: postgre
  template:
      metadata:
        labels:
          app: postgre
      spec:
        containers:
          - name: postgre
            image: postgres:13.16
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_PASSWORD
                value: pg1234
              - name: POSTGRES_USER
                value: ecommerce
              - name: POSTGRES_DB
                value: ecommerce

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fakeshop
spec:  
  selector:
    matchLabels:
      app: fakeshop
  template:
      metadata:
        labels:
          app: fakeshop
      spec:
        containers:
          - name: fakeshop
            image: fabtrindade/fake-shop-desafio:v1
            ports:
              - containerPort: 5000
            env:
              - name: DB_HOST
                value: localhost
              - name: DB_USER
                value: ecommerce
              - name: DB_PASSWORD
                value: pg1234
              - name: DB_NAME
                value: ecommerce
              - name: DB_PORT
                value: "5432"
